### PR TITLE
Providing a sample to use the just installed azure CLI to create an "app"

### PR DESCRIPTION
**Pull request by ebarrielle**
The azure CLI just installed can itself be used to create the Service principal needed for automation.

### CODE REVIEW

**Comment by ojacques** [comment]
Thanks @ebarrielle !
Just one comment: can you move the txt file to a `vagrant/doc` dir and add an hyperlink to azure-CLI-create-SP-sample.txt, from the README?

**Comment by ebarrielle** [comment]
Well you made me start learning the syntax of md files... A good investment! ;-)

**Comment by ebarrielle** [comment]
Oops...

**Comment by ojacques** [comment]
Thanks!

**Pull request merged**
